### ISSUE TITLE
Memory leak creating singletons in moved injector

### ISSUE THREAD

**Issue by sinall** [boost-ext/di#233] opened 2017-08-20 05:03 UTC
I'm using DI for MFC project. Since the CWinApp implementation class need to be defined as static, I have no way to use constructor to inject dependencies.

On the other hand, the actual dialog class needs some dependencies. In my case one of the dependency could be a DI factory. The DI factory needs to be created dynamically in MyApp(extends from CWinApp) and then be passed to the dialog's constructor.

I read issue #225 , but didn't find a way to create a factory explicitly.

```
const auto injector = di::make_injector(
    di::bind<ifactory<CLoginDialog, CWnd*>>().to(factory<CLoginDialog>{})
);
auto loginDialogFactory = injector.create<std::shared_ptr<ifactory<CLoginDialog, CWnd*>>>();
```

> Error when compiling the code:
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2039	'type': is not a member of 'boost::di::v1_1_0::aux::concept_check<boost::di::v1_1_0::concepts::type_<CWnd *>::has_disallowed_qualifiers>'	MyApp	\di-1.1.0\include\boost\di.hpp	1815	

A solution might be creating a middle app, which then could create the dialog for MyApp. However, if I know how to create or get a factory from injector, then the code be simpler.

**Comment by sinall** [comment] 2017-08-20 06:32
It seems that the error is because of pointer type in constructor.

After I use boost::optional<CWnd*> instead of CWnd*, the error was fixed.
But now I'm facing a new problem, one of the underlying dependency is created twice.

Here's example code:
```
class X {
public:
	X() {
	}
};

struct interface1 {
	virtual ~interface1() noexcept = default;
	virtual void dummy1() = 0;
};
//->

struct implementation : interface1 {
	void dummy1() override {}
};

struct implementation_with_args : interface1 {
	implementation_with_args(int i, double d) {
		assert(42 == i);
		assert(87.0 == d);
	}
	void dummy1() override {}
};

struct implementation_with_injected_args : interface1 {
	implementation_with_injected_args(X& x, double d) {
		assert(87.0 == d);
	}
	void dummy1() override {}
};

/*<<example `example` class>>*/
class example {
public:
	example(const ifactory<interface1>& f1, const ifactory<interface1, int, double>& f2, const ifactory<interface1, double>& f3) {
		assert(dynamic_cast<implementation*>(f1.create().get()));
		assert(dynamic_cast<implementation_with_args*>(f2.create(42, 87.0).get()));
		assert(dynamic_cast<implementation_with_injected_args*>(f3.create(87.0).get()));
	}
};

int main() {
	auto module = [] { return di::make_injector(di::bind<>().to(123)); };
	auto injector1 = di::make_injector(module()
		, di::bind<X>().to<X>()
		//<<bind factory interface to implementation>>
		, di::bind<ifactory<interface1>>().to(factory<implementation>{})

		//<<bind factory interface with parameters to implementation_with_args>>
		, di::bind<ifactory<interface1, int, double>>().to(factory<implementation_with_args>{})

		//<<bind factory interface with some parameters injected to implementation_with_injected_args>>
		, di::bind<ifactory<interface1, double>>().to(factory<implementation_with_injected_args>{})
	);
	// clang-format on

	/*<<create `example`>>*/
	injector1.create<std::shared_ptr<X>>(); // Create X once
	injector1.create<example>(); // Create X twice
}

```

I'm thinking a more smarter factory could capture the dependencies, store them, pass them to the constructor when creating the actual object.

**Comment by kanstantsin-chernik** [comment] 2017-12-02 09:45
@sinall The problem is in moving injector in factory. When you call singleton instance it is already different class.
To fix your problem just use shared scope for X `di::bind<X>().to<X>().in(shared)`. It will be successfully moved between injectors.

**Comment by kanstantsin-chernik** [comment] 2017-12-02 09:53
BTW, it seems that creating singletons in factory leads to memory leaks

**Comment by kanstantsin-chernik** [comment] 2018-11-29 23:36
I guess we can close the issue. It is just a side effect of using static singletons. Now we have `shared_config` where we can avoid this side effect.

**Closed as completed by kanstantsin-chernik** 2018-11-29 23:36 UTC
Labels: bug
