### ISSUE TITLE
[test] exposed injector with the same bindings

### ISSUE THREAD

**Issue by sian-kirk** [boost-ext/di#161] opened 2015-11-09 21:47 UTC
auto injector i1 = make_injector(m1());
assert(42 == i1.create<int>());

auto injector i2 = make_injector(m2());
assert(77 == i1.create<int>());

assert(42 == i1.create<int>());

**Comment by kris-jusiak** [comment] 2015-11-13 17:53
duplicate of #155

**Closed as completed** 2015-11-13 17:54 UTC
